---
- name: Update package cache and upgrade packages
  ansible.builtin.package:
    name: '*'
    state: latest
    update_cache: true
  register: package_update
  failed_when: package_update.failed
  ignore_errors: yes
  notify: restart necessary services

- name: Fail if package upgrade failed
  ansible.builtin.fail:
    msg: "⛔ Upgrade failed on {{ inventory_hostname }}. See logs for details."
  when: package_update is failed

- name: Log upgrade summary
  ansible.builtin.debug:
    msg:
      - "Changed: {{ package_update.changed }}"
      - "Failures: {{ package_update.failed }}"
      - "Details: {{ package_update.results|default(package_update) }}"