---
- name: Update packages on all servers
  hosts: all
  become: yes
  tasks:
    - name: Update package cache and upgrade packages
      ansible.builtin.package:
        name: '*'
        state: latest
